//
// Created by bumman on 20/12/2021.
//

#ifndef NETWORKPROGRAM_CONSTANT_H
#define NETWORKPROGRAM_CONSTANT_H

#define MAX_LEN_BUFF 1024
#define LOGIN "1"
#define HOME_SHOW "2"
#define LOGIN_SUCCESS "s0"
#define SHOW_PLACE "3"
#define ADD_FRIEND "4"
#define SHARE_SHOW_PLACE "5"
#define SHARE_SHOW_FRIEND "6"
#define REGISTER "7"
#define REGISTER_SUCCESS "s0"
#define ADDFRIEND "15"
#define ADDFRIEND_SUCCESS "150"
#define FRIEND_EXIST "152"
#define SEND_END "S1"
#define SHOW_FRIEND_LIST "16"
#define SHOW_USER_LIST "17"
#define SHOW_FRIEND_REQUEST "18"
#define ACCEPT_FRIEND "19"
#define ACCEPT_FRIEND_SUCCESS "190"
#define SHARE_PLACE "20"
#define SHAREPLACE_SUCCESS "200"
#define PLACE_EXIST "202"
#define ADD_PLACE "8"
#define ADD_PLACE_OK "81"
#define ADD_PLACE_ERR "80"
#define REMOVE_PLACE "9"
#define REMOVE_PLACE_OK "91"
#define REMOVE_PLACE_ERROR "90"
#define SEND_END "-1"


#endif //NETWORKPROGRAM_CONSTANT_H
