//
// Created by bumman on 20/12/2021.
//

#ifndef NETWORKPROGRAM_CONSTANT_H
#define NETWORKPROGRAM_CONSTANT_H

#define MAX_LEN_BUFF 1024
#define LOGIN "1"
#define HOME_SHOW "2"
#define LOGIN_SUCCESS "s0"
#define SHOW_PLACE "3"
#define ADD_FRIEND "4"
#define SHARE_SHOW_PLACE "5"
#define SHARE_SHOW_FRIEND "6"
#define REGISTER "7"
#define REGISTER_SUCCESS "s0"
#define ADDFRIEND "15"
#define ADDFRIEND_SUCCESS "150"
#define SEND_END "S1"
#define SHOW_FRIEND_LIST "16"
#define SHOW_USER_LIST "17"
#define SHOW_FRIEND_REQUEST "18"


#endif //NETWORKPROGRAM_CONSTANT_H
